---
- hosts: localhost
  vars:
    deb_ubu_mapping:
      stretch: xenial
      jessie: trusty
      wheezy: precise

    apt_keys_url:
    - id: 592073D4
      url: https://installer.id.ee/media/install-scripts/ria-public.key
    - id: C6C83D68
      url: https://installer.id.ee/media/install-scripts/C6C83D68.pub
    apt_keys_srv:
    - id: EEA14886
      keyserver: keyserver.ubuntu.com

    apt_repos:
    - deb http://deb.debian.org/debian/ {{ansible_distribution_release}} main non-free contrib
    - deb http://deb.debian.org/debian/ {{ansible_distribution_release}}-updates main contrib non-free
    - deb http://security.debian.org/ {{ansible_distribution_release}}/updates main contrib non-free
    - deb https://installer.id.ee/media/ubuntu/ {{deb_ubu_mapping[ansible_distribution_release]}} main
    - deb http://security.debian.org/ jessie/updates main contrib non-free
    - deb http://ppa.launchpad.net/webupd8team/java/ubuntu {{deb_ubu_mapping[ansible_distribution_release]}} main

#    - deb [trusted=yes] https://people.debian.org/~mpitt/tmp/systemd-master-20170225/ /
#    - deb https://apt.dockerproject.org/repo debian-stretch main
#    - deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
#    - deb http://download.virtualbox.org/virtualbox/debian stretch contrib

    apt_packages:
    - [awscli,python-boto,python-wheel]
    - [ca-certificates,openssl,openssh-client,openvpn,openvpn-systemd-resolved,sshpass]
    - [mercurial,git,git-man,pwgen,jq,htop,iw,wireless-tools,wpasupplicant,locales,lsof,mc,mariadb-client,nano,nmap,powertop,upower]
    - [tar,unzip,gzip,xz-utils,zip]
    - [xauth,xfce4-screenshooter,xfce4-settings,xfce4-xkb-plugin,xfce4-terminal,xfce4-panel,xfce4-pulseaudio-plugin,xorg,xserver-common,xserver-xorg,xterm,i3,i3lock,i3status,i3-wm,dunst,colord]
    - [abiword,abiword-plugin-grammar,gnumeric,gnumeric-plugins-extra,smplayer,chromium,gparted,wireshark,wireshark-qt,keepassx]
    - [paman,pavucontrol,pavumeter,pulseaudio,pulseaudio-utils]
    - [open-eid,gcc]
    - [oracle-java8-installer,oracle-java8-set-default]

    idea_version: 2017.1.2
    terraform_version: 0.9.6
    maven_version: 3.5.0

  tasks:
  - apt_key: id={{item.id|default(None)}} url={{item.url|default(None)}} state=present
    with_items: "{{apt_keys_url}}"
  - apt_key: id={{item.id|default(None)}} keyserver={{item.keyserver|default(None)}} state=present
    with_items: "{{apt_keys_srv}}"

  - apt_repository: repo={{item}} state=present
    with_items: "{{apt_repos}}"

  - copy: content="" dest=/etc/apt/sources.list

  - apt: update_cache=yes upgrade=dist

  - debconf: name=oracle-java8-installer question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - apt: pkg={{ item }} autoremove=yes install_recommends=no update_cache=yes state=latest
    with_items: "{{apt_packages}}"

  - file: path=/opt/idea/{{idea_version}}/ mode=0755 state=directory
  - unarchive: src=https://download-cf.jetbrains.com/idea/ideaIU-{{idea_version}}.tar.gz dest=/opt/idea/{{idea_version}}/ remote_src=True extra_opts="--strip-components=1" creates=/opt/idea/{{idea_version}}/bin
  - file: src=/opt/idea/{{idea_version}}/bin/idea.sh dest=/usr/local/bin/idea state=link

  - file: path=/opt/terraform/{{terraform_version}}/ mode=0755 state=directory
  - unarchive: src=https://releases.hashicorp.com/terraform/{{terraform_version}}/terraform_{{terraform_version}}_linux_amd64.zip dest=/opt/terraform/{{terraform_version}}/ remote_src=True creates=/opt/terraform/{{terraform_version}}/terraform
  - file: src=/opt/terraform/{{terraform_version}}/terraform dest=/usr/local/bin/terraform state=link

  - file: path=/opt/maven/{{maven_version}}/ mode=0755 state=directory
  - unarchive: src=https://www-eu.apache.org/dist/maven/maven-3/{{maven_version}}/binaries/apache-maven-{{maven_version}}-bin.tar.gz dest=/opt/maven/{{maven_version}}/ remote_src=True extra_opts="--strip-components=1" remote_src=True creates=/opt/maven/{{maven_version}}/bin/mvn
  - file: src=/opt/maven/{{maven_version}}/bin/mvn dest=/usr/local/bin/mvn state=link


