---
- hosts: localhost
  vars:
    idea_version: 2017.1.2
  tasks:

  - apt: pkg={{ item }} update_cache=yes state=latest
    with_items:
    - i3
    - i3lock
    - i3status
    - xfce4-screenshooter
    - xfce4-terminal
    - dmenu

  - file: path=/opt/idea/{{idea_version}} mode=0755 state=directory
  - unarchive: url=https://download-cf.jetbrains.com/idea/ideaIU-{{idea_version}}.tar.gz dest=/opt/idea/{{idea_version}} remote_src=True
