---
- hosts: localhost

  tasks:

  - apt: pkg={{ item }} update_cache=yes state=latest
    with_items:
    - i3
    - i3lock
    - i3status
    - xfce4-screenshooter
    - xfce4-terminal
    - dmenu

#  - unarchive: url=https://download-cf.jetbrains.com/idea/ideaIU-2017.1.2.tar.gz
